name: 'pixideo'
description: 'Experimental Create Video Using Flutter Widget'
version: '0.0.1'
repository: 'https://github.com/azkadev/pixideo'
homepage: 'https://github.com/azkadev/pixideo'
documentation: 'https://github.com/azkadev/pixideo'
issue_tracker: 'https://github.com/azkadev/pixideo/issues'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://www.patreon.com/c/azkadev'
  - 'https://opencollective.com/azkadev'
  - 'https://paypal.me/azkaaxeliongibran'
  - 'https://paypal.me/azkadev'
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  collection: '^1.19.0'
  equatable: '^2.0.3'
  ffi: '^2.1.4'
  flutter:
    sdk: 'flutter'
  path: '^1.9.0'
  image: "^4.5.4"
dev_dependencies:
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: 'flutter'
flutter: null
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
dependency_overrides:
  camera_android_camerax: '0.6.15'
  http:
    path: '../../../../../../.pub-cache/hosted/pub.dev/http-1.3.0'
  mime: '^2.0.0'
  path_provider_android: '2.2.17'
  pointycastle: '^4.0.0'
